---
- name: Set Time Zone
  hosts: capa1
  user: equiros
  gather_facts: False
  tasks:
    - name: Set timezone variables
      copy: content='America/Santiago'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
